# -----------------------------------------------------------------------------
# apk dependencies
# -----------------------------------------------------------------------------
FROM node:9.7.0-alpine as apk-dependencies
WORKDIR /app

# Install system dependencies.
RUN apk add --update --no-cache --virtual .apk git python make g++ libsecret-dev

# -----------------------------------------------------------------------------
# npm dependencies
# -----------------------------------------------------------------------------
FROM apk-dependencies as npm-dependencies

COPY packages/exchange-aggregator/package.json packages/exchange-aggregator/package.json
COPY packages/graphql-schema/package.json packages/graphql-schema/package.json
COPY packages/graphql-server/package.json packages/graphql-server/package.json
COPY packages/melon.js/package.json packages/melon.js/package.json
COPY packages/manager-components/package.json packages/manager-components/package.json
COPY packages/manager-interface/package.json packages/manager-interface/package.json
COPY package.json yarn.lock ./

# Install node dependencies and clean up afterwards.
RUN yarn install --ignore-engines --frozen-lockfile --pure-lockfile --production && \
  cp -R node_modules node_modules_production && \
  yarn install --ignore-engines --frozen-lockfile --pure-lockfile && \
  yarn cache clean && \
  apk del .apk

# -----------------------------------------------------------------------------
# base development image
# -----------------------------------------------------------------------------
FROM node:9.7.0-alpine as node-development
WORKDIR /app

COPY --from=npm-dependencies /app/node_modules node_modules
COPY package.json yarn.lock ./

# -----------------------------------------------------------------------------
# base production image
# -----------------------------------------------------------------------------
FROM node:9.7.0-alpine as node-production
WORKDIR /app

COPY --from=npm-dependencies /app/node_modules_production node_modules
COPY package.json yarn.lock ./
