version: "3.4"

services:
  manager:
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./tests:/app/tests
      - ./introspect:/app/introspect
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./tslint.json:/app/tslint.json
      - ./jest.config.js:/app/jest.config.js
      - ./jest.setup.js:/app/jest.setup.js
      - ./next.config.js:/app/next.config.js
      - ./next.config.dist.js:/app/next.config.dist.js
      - ./next.routes.js:/app/next.routes.js
      - ./babel.config.js:/app/babel.config.js
      - ./postcss.config.js:/app/postcss.config.js
      - ./backpack.config.js:/app/backpack.config.js
      - ./.babelrc:/app/.babelrc
      - ./.prettierrc:/app/.prettierrc
      - ./.prettierignore:/app/.prettierignore
    ports:
      - "3000:3000"
