mutation estimateApproveTransferMutation(
  $investmentAmount: String!
  $investmentAsset: String!
  $fundAddress: String!
) {
  estimate: estimateApproveTransfer(
    investmentAmount: $investmentAmount
    investmentAsset: $investmentAsset
    fundAddress: $fundAddress
  ) @account {
    data
    from
    gas
    gasPrice
    to
    value
  }
}

mutation executeApproveTransferMutation(
  $data: String!
  $from: String!
  $gas: String!
  $gasPrice: String!
  $to: String!
  $value: String!
  $investmentAmount: String!
  $investmentAsset: String!
  $fundAddress: String!
) {
  execute: executeApproveTransfer(
    investmentAmount: $investmentAmount
    investmentAsset: $investmentAsset
    fundAddress: $fundAddress
    unsigned: {
      data: $data
      from: $from
      gas: $gas
      gasPrice: $gasPrice
      to: $to
      value: $value
    }
  ) @sign @account
}
