mutation EstimateCancelOrderMutation($id: String!, $exchange: ExchangeEnum!) {
  estimate: estimateCancelOrder(id: $id, exchange: $exchange) @account {
    data
    from
    gas
    gasPrice
    to
    value
  }
}

mutation ExecuteCancelOasisDexOrderMutation(
  $data: String!
  $from: String!
  $gas: String!
  $gasPrice: String!
  $to: String!
  $value: String!
  $exchange: ExchangeEnum!
) {
  execute: executeCancelOrder(
    unsigned: {
      data: $data
      from: $from
      gas: $gas
      gasPrice: $gasPrice
      to: $to
      value: $value
    }
    exchange: $exchange
  ) @sign @account
}
