mutation estimateNothing($nothing: Boolean) {
  estimate: estimateNothing(nothing: $nothing) @account
}

mutation estimateRequestInvestmentMutation(
  $investmentAmount: String!
  $investmentAsset: String!
  $fundAddress: String!
  $maxPrice: String
) {
  estimate: estimateRequestInvestment(
    investmentAmount: $investmentAmount
    investmentAsset: $investmentAsset
    fundAddress: $fundAddress
    maxPrice: $maxPrice
  ) @account {
    data
    from
    gas
    gasPrice
    to
    value
    amguInEth {
      token {
        symbol
        decimals
      }
      quantity
    }
    incentiveInEth {
      token {
        symbol
        decimals
      }
      quantity
    }
  }
}

mutation executeRequestInvestmentMutation(
  $data: String!
  $from: String!
  $gas: String!
  $gasPrice: String!
  $to: String!
  $value: String!
  $fundAddress: String!
) {
  execute: executeRequestInvestment(
    fundAddress: $fundAddress
    unsigned: {
      data: $data
      from: $from
      gas: $gas
      gasPrice: $gasPrice
      to: $to
      value: $value
    }
  ) @sign @account
}

mutation estimateExecuteRequestMutation($fundAddress: String!) {
  estimate: estimateExecuteRequest(fundAddress: $fundAddress) @account {
    data
    from
    gas
    gasPrice
    to
    value
    amguInEth {
      token {
        symbol
        decimals
      }
      quantity
    }
    incentiveInEth {
      token {
        symbol
        decimals
      }
      quantity
    }
  }
}

mutation executeExecuteRequestMutation(
  $data: String!
  $from: String!
  $gas: String!
  $gasPrice: String!
  $to: String!
  $value: String!
  $fundAddress: String!
) {
  execute: executeExecuteRequest(
    fundAddress: $fundAddress
    unsigned: {
      data: $data
      from: $from
      gas: $gas
      gasPrice: $gasPrice
      to: $to
      value: $value
    }
  ) @sign @account
}

mutation estimateCancelRequestMutation($fundAddress: String!) {
  estimate: estimateCancelRequest(fundAddress: $fundAddress) @account {
    data
    from
    gas
    gasPrice
    to
    value
  }
}

mutation executeCancelRequestMutation(
  $data: String!
  $from: String!
  $gas: String!
  $gasPrice: String!
  $to: String!
  $value: String!
  $fundAddress: String!
) {
  execute: executeCancelRequest(
    fundAddress: $fundAddress
    unsigned: {
      data: $data
      from: $from
      gas: $gas
      gasPrice: $gasPrice
      to: $to
      value: $value
    }
  ) @sign @account
}
