mutation EstimateMakeOrderMutation(
  $exchange: ExchangeEnum!
  $buyToken: String!
  $buyQuantity: String!
  $sellToken: String!
  $sellQuantity: String!
) {
  estimate: estimateMakeOrder(
    exchange: $exchange
    buyToken: $buyToken
    buyQuantity: $buyQuantity
    sellToken: $sellToken
    sellQuantity: $sellQuantity
  ) @account {
    data
    from
    gas
    gasPrice
    to
    value
    ... on UnsignedTransactionWithOrder {
      signedOrder
    }
  }
}

mutation ExecuteMakeOrderMutation(
  $data: String!
  $from: String!
  $gas: String!
  $gasPrice: String!
  $to: String!
  $value: String!
  $exchange: ExchangeEnum!
  $signedOrder: String
) {
  execute: executeMakeOrder(
    exchange: $exchange
    signedOrder: $signedOrder
    unsigned: {
      data: $data
      from: $from
      gas: $gas
      gasPrice: $gasPrice
      to: $to
      value: $value
    }
  ) @sign @account
}
