mutation estimateMakeOrderMutation(
  $exchange: ExchangeEnum!
  $buyToken: String!
  $buyQuantity: String!
  $sellToken: String!
  $sellQuantity: String!
) {
  estimate: estimateMakeOrder(
    exchange: $exchange
    buyToken: $buyToken
    buyQuantity: $buyQuantity
    sellToken: $sellToken
    sellQuantity: $sellQuantity
  ) @account {
    data
    from
    gas
    gasPrice
    to
    value
  }
}

mutation executeMakeOrderMutation(
  $data: String!
  $from: String!
  $gas: String!
  $gasPrice: String!
  $to: String!
  $value: String!
  $exchange: ExchangeEnum!
) {
  execute: executeMakeOrder(
    exchange: $exchange
    unsigned: {
      data: $data
      from: $from
      gas: $gas
      gasPrice: $gasPrice
      to: $to
      value: $value
    }
  ) @sign @account {
    id
    trade {
      base {
        token {
          symbol
        }
      }
      quote {
        token {
          symbol
        }
      }
    }
    price
    volume
    type
    exchange
    metadata {
      isActive
    }
  }
}

mutation estimateTakeOasisDexOrderMutation(
  $id: String!
  $fillQuantity: String
) {
  estimate: estimateTakeOasisDexOrder(id: $id, fillQuantity: $fillQuantity)
    @account {
    data
    from
    gas
    gasPrice
    to
    value
  }
}

mutation executeTakeOasisDexOrderMutation(
  $data: String!
  $from: String!
  $gas: String!
  $gasPrice: String!
  $to: String!
  $value: String!
) {
  execute: executeTakeOasisDexOrder(
    unsigned: {
      data: $data
      from: $from
      gas: $gas
      gasPrice: $gasPrice
      to: $to
      value: $value
    }
  ) @sign @account {
    id
    trade {
      base {
        token {
          symbol
        }
      }
      quote {
        token {
          symbol
        }
      }
    }
    price
    volume
    type
    exchange
  }
}
