mutation EstimateTakeOrderMutation(
  $id: String
  $exchange: ExchangeEnum!
  $buyToken: String
  $buyQuantity: String
  $sellToken: String
) {
  estimate: estimateTakeOrder(
    id: $id
    exchange: $exchange
    buyToken: $buyToken
    buyQuantity: $buyQuantity
    sellToken: $sellToken
  ) @account {
    data
    from
    gas
    gasPrice
    to
    value
  }
}

mutation ExecuteTakeOrderMutation(
  $data: String!
  $from: String!
  $gas: String!
  $gasPrice: String!
  $to: String!
  $value: String!
  $exchange: ExchangeEnum!
) {
  execute: executeTakeOrder(
    unsigned: {
      data: $data
      from: $from
      gas: $gas
      gasPrice: $gasPrice
      to: $to
      value: $value
    }
    exchange: $exchange
  ) @sign @account {
    id
    trade {
      base {
        token {
          symbol
        }
      }
      quote {
        token {
          symbol
        }
      }
    }
    price
    volume
    type
    exchange
  }
}
