query OpenOrdersQuery($fundAddress: String!) {
  openOrders(fundAddress: $fundAddress) {
    id
    price
    volume
    trade {
      base {
        token {
          symbol
        }
      }
      quote {
        token {
          symbol
        }
      }
    }
    type
    exchange
    ... on OasisDexOrder {
      metadata {
        timestamp
      }
    }
  }
}
